apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameengine-deployment
  labels:
    app: gameengine-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: gameengine-deployment
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: gameengine-deployment
    spec:
      containers:
        - name: gameengine-deployment
          image: hitanshu/gameengine
          command: ["/app/gameengine"]
          args:
            - --address=:50061
