apiVersion: v1
kind: Service
metadata:
  name: gameengine-sevice
spec:
  type: ClusterIP
  selector:
    app: gameengine-sevice
  ports:
    - name: grpc
      port: 50061
      targetPort: 50061
      protocol: TCP
