// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gameengine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameengineClient is the client API for Gameengine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameengineClient interface {
	SetScore(ctx context.Context, in *SetScoreRequest, opts ...grpc.CallOption) (*SetScoreResponse, error)
	GetSize(ctx context.Context, in *GetSizeRequest, opts ...grpc.CallOption) (*GetSizeResponse, error)
}

type gameengineClient struct {
	cc grpc.ClientConnInterface
}

func NewGameengineClient(cc grpc.ClientConnInterface) GameengineClient {
	return &gameengineClient{cc}
}

func (c *gameengineClient) SetScore(ctx context.Context, in *SetScoreRequest, opts ...grpc.CallOption) (*SetScoreResponse, error) {
	out := new(SetScoreResponse)
	err := c.cc.Invoke(ctx, "/gameengine.v1.gameengine/SetScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameengineClient) GetSize(ctx context.Context, in *GetSizeRequest, opts ...grpc.CallOption) (*GetSizeResponse, error) {
	out := new(GetSizeResponse)
	err := c.cc.Invoke(ctx, "/gameengine.v1.gameengine/GetSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameengineServer is the server API for Gameengine service.
// All implementations must embed UnimplementedGameengineServer
// for forward compatibility
type GameengineServer interface {
	SetScore(context.Context, *SetScoreRequest) (*SetScoreResponse, error)
	GetSize(context.Context, *GetSizeRequest) (*GetSizeResponse, error)
	mustEmbedUnimplementedGameengineServer()
}

// UnimplementedGameengineServer must be embedded to have forward compatible implementations.
type UnimplementedGameengineServer struct {
}

func (UnimplementedGameengineServer) SetScore(context.Context, *SetScoreRequest) (*SetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetScore not implemented")
}
func (UnimplementedGameengineServer) GetSize(context.Context, *GetSizeRequest) (*GetSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSize not implemented")
}
func (UnimplementedGameengineServer) mustEmbedUnimplementedGameengineServer() {}

// UnsafeGameengineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameengineServer will
// result in compilation errors.
type UnsafeGameengineServer interface {
	mustEmbedUnimplementedGameengineServer()
}

func RegisterGameengineServer(s grpc.ServiceRegistrar, srv GameengineServer) {
	s.RegisterService(&Gameengine_ServiceDesc, srv)
}

func _Gameengine_SetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameengineServer).SetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gameengine.v1.gameengine/SetScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameengineServer).SetScore(ctx, req.(*SetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gameengine_GetSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameengineServer).GetSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gameengine.v1.gameengine/GetSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameengineServer).GetSize(ctx, req.(*GetSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gameengine_ServiceDesc is the grpc.ServiceDesc for Gameengine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gameengine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gameengine.v1.gameengine",
	HandlerType: (*GameengineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetScore",
			Handler:    _Gameengine_SetScore_Handler,
		},
		{
			MethodName: "GetSize",
			Handler:    _Gameengine_GetSize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/gameengine/v1/gameengine.proto",
}
