apiVersion: apps/v1
kind: Deployment
metadata:
  name: highscore-deployment
  labels:
    app: highscore-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: highscore-deployment
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: highscore-deployment
    spec:
      containers:
        - name: highscore-deployment
          image: hitanshu/highscore
          command: ["/app/highscore"]
          args:
            - --address=:50051
