apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  type: ClusterIP
  selector:
    app: bff-service
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
